#!/usr/bin/env npx tsx
/**
 * seed-board-map.ts — Bootstrap board_channel_map.yaml from live data.
 *
 * Usage:
 *   npx tsx scripts/seed-board-map.ts [--boards-dir PATH] [--guild GUILD_ID]
 *
 * Behavior:
 *   1. Scans kanban board slugs from the local boards directory.
 *   2. Fetches text channels from the AGENTIC-OS Discord guild.
 *   3. Matches slugs to channel names (case-insensitive).
 *   4. Emits valid YAML to stdout (does NOT write the file).
 *
 * Requires:
 *   - DISCORD_BOT_TOKEN environment variable (or in ../.env)
 *
 * Match strategy:
 *   Case-insensitive: board slug == Discord channel name.
 *   Unmatched boards are printed as YAML comments.
 */

import { readdirSync, existsSync, readFileSync } from "fs";
import { resolve, join } from "path";
import { homedir } from "os";

// ── Parse args ─────���────────────────────────────────────────────────
const args = process.argv.slice(2);
let boardsDir = join(homedir(), ".hermes", "kanban", "boards");
// REPLACE ME: set AGENTIC_GUILD_ID env var or pass --guild <id>
let guildId = process.env.AGENTIC_GUILD_ID ?? "<your-guild-id>";

for (let i = 0; i < args.length; i++) {
	if (args[i] === "--boards-dir" && args[i + 1]) {
		boardsDir = resolve(args[++i]);
	} else if (args[i] === "--guild" && args[i + 1]) {
		guildId = args[++i];
	} else if (args[i] === "--help" || args[i] === "-h") {
		console.log(`Usage: npx tsx scripts/seed-board-map.ts [--boards-dir PATH] [--guild GUILD_ID]`);
		console.log(`  Scans kanban boards and Discord channels, emits board_channel_map.yaml to stdout.`);
		process.exit(0);
	}
}

// ── Load Discord token ──────────────────────────────────────────────
function loadEnvToken(): string | undefined {
	const envPath = resolve(__dirname, "..", ".env");
	if (!existsSync(envPath)) return undefined;
	const raw = readFileSync(envPath, "utf-8");
	for (const line of raw.split("\n")) {
		const trimmed = line.trim();
		if (trimmed.startsWith("DISCORD_BOT_TOKEN=")) {
			return trimmed.slice("DISCORD_BOT_TOKEN=".length).replace(/^["']|["']$/g, "");
		}
	}
	return undefined;
}

const discordToken = process.env.DISCORD_BOT_TOKEN || loadEnvToken();
if (!discordToken) {
	console.error("ERROR: DISCORD_BOT_TOKEN not found in env or .env file.");
	process.exit(1);
}

// ── Discover board slugs ────────────────────────────────────────────
function discoverBoards(dir: string): string[] {
	if (!existsSync(dir)) {
		console.error(`ERROR: Boards directory does not exist: ${dir}`);
		process.exit(1);
	}
	return readdirSync(dir, { withFileTypes: true })
		.filter((d) => d.isDirectory() && existsSync(join(dir, d.name, "kanban.db")))
		.map((d) => d.name);
}

// ── Fetch Discord channels ────────────��─────────────────────────────
interface DiscordChannel {
	id: string;
	name: string;
	type: number;
	parent_id: string | null;
}

async function fetchGuildChannels(guild: string, token: string): Promise<DiscordChannel[]> {
	const res = await fetch(`https://discord.com/api/v10/guilds/${guild}/channels`, {
		headers: {
			Authorization: `Bot ${token}`,
			"Content-Type": "application/json",
		},
	});
	if (!res.ok) {
		console.error(`ERROR: Discord API returned ${res.status} ${res.statusText}`);
		process.exit(1);
	}
	return (await res.json()) as DiscordChannel[];
}

// ── Main ────────────���─────────────────────────────���─────────────────
async function main() {
	const boards = discoverBoards(boardsDir);
	const channels = await fetchGuildChannels(guildId, discordToken!);

	// Only text channels (type 0)
	const textChannels = channels.filter((c) => c.type === 0);

	// Build lookup: lowercase channel name → channel
	const channelsByName = new Map<string, DiscordChannel>();
	for (const ch of textChannels) {
		channelsByName.set(ch.name.toLowerCase(), ch);
	}

	// Match
	const matched: { slug: string; channel_id: string; channel_name: string }[] = [];
	const unmatched: string[] = [];

	for (const slug of boards) {
		const ch = channelsByName.get(slug.toLowerCase());
		if (ch) {
			matched.push({ slug, channel_id: ch.id, channel_name: ch.name });
		} else {
			unmatched.push(slug);
		}
	}

	// Emit YAML to stdout
	const lines: string[] = [];
	lines.push("# Board-to-Channel Mapping Registry");
	lines.push("# ===================================");
	lines.push("# Generated by: npx tsx scripts/seed-board-map.ts");
	lines.push(`# Generated at: ${new Date().toISOString()}`);
	lines.push(`# Guild: ${guildId}`);
	lines.push(`# Boards scanned: ${boards.length}`);
	lines.push(`# Matched: ${matched.length}, Unmatched: ${unmatched.length}`);
	lines.push("#");
	lines.push("# Review this output before committing to board_channel_map.yaml.");
	lines.push("# Entries marked required: true will block worker boot if the channel 404s.");
	lines.push("");
	lines.push("boards:");

	for (const m of matched) {
		lines.push(`  ${m.slug}:`);
		lines.push(`    channel_id: "${m.channel_id}"  # discord channel: ${m.channel_name}`);
		lines.push(`    required: false`);
	}

	if (unmatched.length > 0) {
		lines.push("");
		lines.push("# ── Unmatched boards (no matching Discord channel name) ──");
		for (const slug of unmatched) {
			lines.push(`# unmatched: ${slug}`);
		}
	}

	console.log(lines.join("\n"));
}

main().catch((err) => {
	console.error(`FATAL: ${err.message}`);
	process.exit(1);
});
